FROM mariadb:11.7.2
RUN apt-get update && apt-get install -y --no-install-recommends git openssh-client rsync tzdata \
 && rm -rf /var/lib/apt/lists/*
COPY docker/wiki-backup.sh /wiki-backup.sh
ENTRYPOINT []
CMD ["sh", "/wiki-backup.sh"]
